server:
  port: 8080

spring:
  application:
    name: ms-campuslab-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          # Id. de directorio (inquilino)
          issuer-uri: https://login.microsoftonline.com/aff2eb38-d6cf-4220-8527-53f1cb6aed15/v2.0
          # URI de id. de aplicación del BFF
          audiences: api://8d19bb45-1842-43ce-b76c-4513b979df81

services:
  catalog-url: http://catalog-service:8082
  bookings-url: http://bookings-service:8081